name: Check generated code
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  check-proto:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # we need a .git directory to run git diff
      -
        name: "Check protobuf generated code"
        run: scripts/check-generated.sh